INSERT INTO User(username,name,password) VALUES ('John_rdoe3','John Doe','xjaldjfaojvoew89403530tepqfapfekafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('ibanr_dorta','iban dorta','xxjaldjfavoifjoew89403530teefapfkafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('Joser_Antonio','Jose Antonio','xxxjvaldjfaoifjoew89403e530tepqfapafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('Javirer_Padron','Javier Padrón','xxxxvxjaldjfaoifjoew89e403530tepqfakafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('Nazarret_Rios','Nazaret Rios','jaxxxxxxvldjfaoifjoew89403530tepapfkafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('Manrolo_Antunez ','Manolo_Antunez','jalxxxvdjfaoifedjoew894030tepqfapfkafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('Abrraham_Cabrera','Abraham Cabrera','jaldjvfaoxxxifjoew894530tepqfapfkafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('Samruel_Brito','Samuel Brito','jaldjfafjoew8vxxxx9403530tepqfapfkafkpoewgiqte0t');
INSERT INTO User(username,name,password) VALUES ('Lucria_Sanchez','Lucia Sanchez','jalxxxdjfifjoedw89403530tepqefapfkafkpoewgiqte0t');